baseurl = "https://updates.scoutred.com/"
languageCode = "en-us"
theme = "hugo-incorporated"

[params]
	[params.inc]
	title = "Scoutred Blog"
	subtitle = ""
	cover_image = "blog-cover.jpg"
	logo = "logo.png"

	# Company information
	company = "Scoutred"
	url = "https://scoutred.com?utm_source=blog&utm_medium=logo-click"
	github =  "scoutred"
	twitter = "scoutredhq"

	# Product Information
	pricing_link = "https://scoutred.com/pricing?utm_source=blog&utm_medium=pricing"
	login_link = "https://scoutred.com/maps/auth/login?utm_source=blog&utm_medium=login"
	signup_link = "https://scoutred.com/maps/auth/signUp?utm_source=blog&utm_medium=signup"
	blog_link = "https://updates.scoutred.com/"
	maps_link = "https://scoutred.com/maps?utm_source=blog"
	tagline = ""

	[params.inc.analytics]
	googleid = "UA-51537973-2"