baseurl = "http://blog.scoutred.com"
languageCode = "en-us"
theme = "hugo-incorporated"

[params]

	[params.inc]
	# Blog Information
	title = "Progress"
	subtitle = "Always be improving"
	cover_image = "blog-cover.jpg"
	logo = "logo.png"

	# Company information
	company = "ScoutRED"
	url = "https://scoutred.com/"
	# facebook =    ""
	# github =      "scoutred"
	# twitter =     nw_iw
	# gplus =       ''
	# about_link =  http://nilproductions.com/about/

	# Product Information
	product_link = "https://scoutred.com/"
	tagline = "Land use search"

	[params.inc.analytics]
	googleid = "UA-51537973-2"